### ISSUE TITLE
Minor Fixes

### ISSUE THREAD

**Issue by SauravMaheshkar** [vballoli/vit-flax#2]
[Wrong gfile calls](https://github.com/vballoli/vit-flax/blob/ffbe0d9b005cf0dfaec1a33a8ce3eb69c4b6b46a/examples/cifar_train.py#L37)
```
if not gfile.Exists(output_dir):
    gfile.MakeDirs(output_dir)
```

## Wrong File name

**The file in the examples dir should be named `configs` instead of `config`**

# Expected 

`exists` and `makedirs`

# Miscellaneous 

Simple Linter errors I guess

**Comment by vballoli** [comment]
Hey, I'm really sorry about the late reply. Could you send a PR for the same if possible? I'll probably take time to fix it.
